-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Machine: 127.0.0.1
-- Gegenereerd op: 25 apr 2016 om 10:27
-- Serverversie: 5.6.21
-- PHP-versie: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Databank: `wordpress_uwv`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `uwv_wajong`
--

CREATE TABLE IF NOT EXISTS `uwv_wajong` (
  `Vacaturetitel` varchar(200) NOT NULL,
  `Vacaturenummer` varchar(200) NOT NULL,
  `Branche` varchar(200) NOT NULL,
  `Functieomschrijving` varchar(200) NOT NULL,
  `Extrafunctieomschrijving` varchar(200) NOT NULL,
  `Functieeisen` varchar(200) NOT NULL,
  `Werklocatiespecificatie` varchar(200) NOT NULL,
  `Arbeidstijdmin` varchar(200) NOT NULL,
  `Arbeidstijdmax` varchar(200) NOT NULL,
  `Toelichtingarbeidsvoorwaarden` varchar(200) NOT NULL,
  `Normalewerktijden` varchar(200) NOT NULL,
  `Ploegendienst` varchar(200) NOT NULL,
  `Storingsdienst` varchar(200) NOT NULL,
  `Competentie1` varchar(200) NOT NULL,
  `Competentie2` varchar(200) NOT NULL,
  `Competentie3` varchar(200) NOT NULL,
  `Competentie4` varchar(200) NOT NULL,
  `Competentie5` varchar(200) NOT NULL,
  `Sollicitatiewijze` varchar(200) NOT NULL,
  `Sollemailadres` varchar(200) NOT NULL,
  `Solladresstraatnaamhuisnummer` varchar(200) NOT NULL,
  `Solladrespostcode` varchar(200) NOT NULL,
  `Solladresplaats` varchar(200) NOT NULL,
  `Solladresland` varchar(200) NOT NULL,
  `CPsollprocnaam` varchar(200) NOT NULL,
  `CPsollprocfunctie` varchar(200) NOT NULL,
  `CPsollproctelefoonnummer` varchar(200) NOT NULL,
  `CPsollprocemailadres` varchar(200) NOT NULL,
  `CPInfvacnaam` varchar(200) NOT NULL,
  `CPInfvacfunctie` varchar(200) NOT NULL,
  `CPInfvactelefoonnummer` varchar(200) NOT NULL,
  `CPInfvacemailadres` varchar(200) NOT NULL,
  `Status` varchar(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Gegevens worden geëxporteerd voor tabel `uwv_wajong`
--

INSERT INTO `uwv_wajong` (`Vacaturetitel`, `Vacaturenummer`, `Branche`, `Functieomschrijving`, `Extrafunctieomschrijving`, `Functieeisen`, `Werklocatiespecificatie`, `Arbeidstijdmin`, `Arbeidstijdmax`, `Toelichtingarbeidsvoorwaarden`, `Normalewerktijden`, `Ploegendienst`, `Storingsdienst`, `Competentie1`, `Competentie2`, `Competentie3`, `Competentie4`, `Competentie5`, `Sollicitatiewijze`, `Sollemailadres`, `Solladresstraatnaamhuisnummer`, `Solladrespostcode`, `Solladresplaats`, `Solladresland`, `CPsollprocnaam`, `CPsollprocfunctie`, `CPsollproctelefoonnummer`, `CPsollprocemailadres`, `CPInfvacnaam`, `CPInfvacfunctie`, `CPInfvactelefoonnummer`, `CPInfvacemailadres`, `Status`) VALUES
('Medew. bakkerij/chauffeur (Wajong)', '1034516', 'Transport en logistiek', 'Voor een bakkerij in Schoonebeek zijn we op zoek naar een medewerker bakkerij/chauffeur. U gaat brood snijden en inpakken en deze bezorgen bij de klanten. U start ''s nachts om 03.00 uur tot ongeveer 0', '', '', 'SCHOONEBEEK', '38', '38', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', 'Op de behoeften en verwachtingen van de "klant" richten', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker werkplaats (Wajong)', '1035016', 'Industrie & Techniek', 'Voor een bedrijf in Emmen zijn we op zoek naar een medewerker werkplaats. U gaat wanden isoleren met glaswol. U gaat stalen constructies in elkaar zetten. U gaat geisoleerde wanden afmonteren en dakle', '', 'U bent flexibel ingesteld en u heeft affiniteit met werken in de bouw. U bent bereid om bij drukte de buitendienst te assisteren.', 'EMMEN', '38', '38', '', 'Normaal', 'Nee', 'Nee', 'Materialen en middelen inzetten', 'Vakdeskundigheid toepassen', 'Instructies en procedures opvolgen', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Verkoopmedewerker (Wajong)', '1035616', 'Detailhandel', 'Voor een bedrijf in Emmen zoeken wij een verkoopmedewerker. Uw taken bestaan uit: orders picken, orders inpakken en verzendklaar maken, licht administratieve werkzaamheden en u helpt klanten aan de ba', '', 'U bent klantvriendelijk en en u heeft affiniteit met brommers.', 'EMMEN', '', '20', '', 'Normaal', 'Nee', 'Nee', 'Presenteren', 'Op de behoeften en verwachtingen van de "klant" richten', 'Instructies en procedures opvolgen', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Online verkoopmedewerker (Wajong)', '1035916', 'Detailhandel', 'Voor een bedrijf in Emmen zoeken wij een online verkoopmedewerker. U gaat foto''s maken van het product, u plaatst deze online, u voert de product omschrijving in en u handelt de verkoop van het produc', '', 'U beheerst de Nederlandse taal, mondeling en schriftelijk goed.', 'EMMEN', '', '20', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', 'Vakdeskundigheid toepassen', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Allround medewerker (Wajong)', '1036716', 'Bouw', 'Voor een bedrijf in Nieuw Buinen zijn we op zoek naar een medewerker. U gaat timmerwerkzaamheden op locatie verrichten. U onderhoud de showtuin. U verricht bestratingswerkzaamheden, inclusief grondwer', '', 'U heeft geen fysieke klachten.', 'NIEUW-BUINEN', '20', '20', '', 'Normaal', 'Nee', 'Nee', 'Materialen en middelen inzetten', 'Instructies en procedures opvolgen', 'Vakdeskundigheid toepassen', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Verkoop- en servicemedew. (Wajong)', '1110716', 'Zakelijke dienstverlening', 'Telefonisch benaderen van ondernemens in het MKB voor prospects en maken van afspraken voor informatieverstrekking. Producten waarvoor afspraken gemaakt worden zijn, computers, computersystemen, telef', '', '- Representatief en klantvriendelijk- Goede telefoonstem - Technische achtergrond is gewenst- Rijbewijs B - Ervaring met telefonische acquisitie- Gestructureerd en planmatig kunnen werken- Ge‹nteresse', 'EMMEN', '20', '20', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', 'Vakdeskundigheid toepassen', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Diamantlaan 1', '9743BA', 'GRONINGEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Buitengewoon opsporingsambtenaar', '1111216', 'Beveiliging en Bewaking', 'Je levert een bijdrage aan de openbare orde, veiligheid en veiligheidsbeleving in het publieke domein. De kerntaken zijn: het controleren en handhaven van specifieke verordeningen, toezien op de orde ', 'het signaleren van en optreden bij incidenten en het aanspreken van mensen op hun gedrag. Tevens ben je aanspreekpunt voor het informeren en verwijzen van reizigers. Daarnaast kun je ingezet worden bi', '#NAAM?', 'EMMEN', '36', '36', '', 'Normaal', 'Nee', 'Nee', 'Met druk en tegenslag omgaan', 'Instructies en procedures opvolgen', 'Presenteren', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Diamantlaan 1', '9743BA', 'GRONINGEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker apotheek (Wajong)', '1112216', 'Zorg & Welzijn', 'Bemannen van een uitgiftepunt voor medicijnen. Ontvangen van klanten op een vriendelijke en prettige wijze, controleren van de identiteit en het afgeven van bestelde medicijnen. Voor en na de uitgifte', '', '- Representatief en klantvriendelijk- Accuraat en servicegerichte instelling- In bezit van rijbewijs en eigen auto- Goede beheersing van de Nederlandse taal in woord en geschrift- Zelfstandig en gestr', 'NIEUW-WEERDINGE', '12', '12', '', 'Normaal', 'Nee', 'Nee', 'Materialen en middelen inzetten', 'Instructies en procedures opvolgen', 'Samenwerken en overleggen', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Diamantlaan 1', '9743BA', 'GRONINGEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Productiemedewerker (Wajong)', '1148116', 'Industrie & Techniek', 'De werkzaamheden bestaan uit: het schoonmaken van machines. Het is een bedrijf dat verschillende soorten netten maakt met machines. Deze machines moeten vrijgemaakt worden van stof. Ook zijn er werkza', '', '', 'EMMEN', '20', '40', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Olivier van Noortstraat 8', '7825VD', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Leerling voeger (Wajong)', '1148316', 'Industrie & Techniek', 'Voor een bedrijf in Emmen zoeken wij een leerling-voeger. Het kan voorkomen dat een klus wordt gedaan voor langere tijd. Er wordt dan een overnachting geregeld (bed en breakfast). Er is een begeleidin', '', 'We zijn bij voorkeur op zoek naar een full-time medewerker, parttime is bespreekbaar.', 'EMMEN', '20', '40', '', 'Normaal', 'Nee', 'Nee', 'Materialen en middelen inzetten', 'Instructies en procedures opvolgen', 'Vakdeskundigheid toepassen', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Olivier van Noortstraat 8', '7825VD', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker supermarkt (Wajong)', '1149216', 'Detailhandel', 'Je gaat alle voorkomende werkzaamheden in de supermarkt verrichten bijv. spiegelen, schoonmaken, vakken vullen etc.', '', 'We zoeken een kandidaat die 32 uur per week beschikbaar is. Dit is in overleg aan te passen naar een ander aantal uren.', 'HOOGEVEEN', '', '32', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', 'Vakdeskundigheid toepassen', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Olivier van Noortstraat 8', '7825VD', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker komkommerkwekerij Wajong', '1149816', 'Agrarische Sector', 'Je verricht repeterende werkzaamheden in een komkommerkwekerij. Het is eenvoudig werk, maar het kan wel zwaar zijn omdat je de hele dag in 1 gangpad dezelfde werkzaamheden uitvoert. Je hebt niet altij', '', 'Je kunt op den duur zelfstandig werken.', 'EMMEN', '40', '40', '', 'Normaal', 'Nee', 'Nee', 'Kwaliteit leveren', 'Materialen en middelen inzetten', 'Vakdeskundigheid toepassen', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Olivier van Noortstraat 8', '7825VD', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Vrachtwagenpoetser (Wajong)', '1233816', 'Transport en logistiek', 'Voor een bedrijf in Emmen zijn we op zoek naar een vrachtwagen-, autopoetser.', '', 'U kunt netjes werken.', 'EMMEN', '32', '32', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Olivier van Noortstraat 8', '7825VD', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker kwekerij (Wajong)', '1235216', 'Agrarische Sector', 'Je werkt in de kas. Taken: oppotten, verpotten, overzetten, bewateren.', '', 'U bent woonachtig in Klazienaveen of directe omgeving.', 'KLAZIENAVEEN', '24', '32', '', 'Normaal', 'Nee', 'Nee', 'Kwaliteit leveren', 'Vakdeskundigheid toepassen', 'Materialen en middelen inzetten', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 596', '8440AN', 'HEERENVEEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker animatieteam', '1286316', 'Overige / Uniforme beroepen', 'Voor een pretpark in Dalen zijn wij op zoek naar een spontane, klantvriendelijke en gastvrije medewerker die het leuk vindt om kinderen te vermaken en gevoel heeft voor dans.', 'Meet and greet kids (verkleed)Meedoen aan de dagelijkse theatervoorstellingVerschillende animatie activiteiten voor kids', 'Tevens werken in de weekenden.', 'DALEN', '20', '32', '', 'Normaal', 'Nee', 'Nee', 'Op de behoeften en verwachtingen van de "klant" richten', 'Begeleiden', 'Aandacht en begrip tonen', 'Presenteren', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Bedieningsmedewerker attracties', '1287616', 'Overige / Uniforme beroepen', 'Voor verschillende attracties op een attractiepark zoeken we spontane, klantvriendelijke en gastvrije medewerkers voor allerlei werkzaamheden.', 'Attractie bedienenGasten helpen en te woord te staanVeiligheidsregels volgenNetjes en schoonhouden van werkplek', 'Bereidheid om ook tijdens weekenden en feestdagen te werken.', 'SLAGHAREN', '24', '32', '', 'Normaal', 'Nee', 'Nee', 'Presenteren', 'Op de behoeften en verwachtingen van de "klant" richten', 'Aandacht en begrip tonen', 'Begeleiden', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Winkelmedewerker Merchandise', '1289916', 'Overige / Uniforme beroepen', 'Voor verschillende winkels op een attractiepark zoeken wij klantvriendelijke en gastvrije medewerkers voor allerlei werkzaamheden.', 'KassawerkzaamhedenKlanten helpenWinkel netjes houdenSchoonmaakwerkzaamheden', 'Bereidheid om ook tijdens weekenden en feestdagen te werken. Kassa ervaring gewenst.', 'SLAGHAREN', '20', '32', '', 'Normaal', 'Nee', 'Nee', 'Presenteren', 'Op de behoeften en verwachtingen van de "klant" richten', 'Instructies en procedures opvolgen', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Bedieningsmedewerker attracties', '1290916', 'Overige / Uniforme beroepen', 'Voor een attractiepark zoeken we een spontane, klantvriendelijke en gastvrije medewerker voor allerlei werkzaamheden.', 'Attractie bedienenGasten helpen en te woord staanVeiligheidsregels volgenNetjes en schoon houden van werkplek', 'Moeten bereid zijn te werken tijdens weekenden.', 'DALEN', '24', '32', '', 'Normaal', 'Nee', 'Nee', 'Presenteren', 'Op de behoeften en verwachtingen van de "klant" richten', 'Aandacht en begrip tonen', 'Begeleiden', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker Horeca', '1291716', 'Horeca', 'Voor verschillende horeca gelegenheden op een attractiepark zoeken we spontane, klantvriendelijke en gastvrije medewerkers voor allerlei werkzaamheden in de horeca.', 'Bedienen van gastenKlaarzetten van buffettenVoorbereidingen treffen in keukenSchoonmaakwerkzaamheden', 'Bereidheid om ook tijdens weekenden en feestdagen te werken.', 'SLAGHAREN', '24', '32', '', 'Normaal', 'Nee', 'Nee', 'Samenwerken en overleggen', 'Instructies en procedures opvolgen', 'Op de behoeften en verwachtingen van de "klant" richten', 'Met druk en tegenslag omgaan', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Schoonmaakmedewerker', '1293016', 'Interieurverzorging / industri‰le reiniging / schoonmaak', 'Voor verschillende locaties op een attractiepark zoeken we spontane, klantvriendelijke en gastvrije medewerkers voor allerlei schoonmaakwerkzaamheden.', 'Toiletgebouwen schoonmaken op het park en campingKantoorruimtes schoonmaken', 'Bereid om ook tijdens weekenden en feestdagen te werken.', 'SLAGHAREN', '20', '32', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Melker (Wajong)', '251516', 'Agrarische Sector', 'Voor een grote melkveehouderij zijn wij op zoek naar een zelfstandig werkend melker. Het werk zal met name in de middaguren plaatsvinden.', '', 'U moet zelfstandig kunnen werken. I.v.m. de locatie zoeken we iemand die beschikt over eigen vervoer.', 'HOOGHALEN', '15', '15', '', 'Normaal', 'Nee', 'Nee', 'Vakdeskundigheid toepassen', 'Kwaliteit leveren', 'Materialen en middelen inzetten', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 596', '8440AN', 'HEERENVEEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Assistent hovenier (Wajong)', '336116', 'Agrarische Sector', 'U gaat helpen bij onderhoud en aanlegklussen, schoffelen, opruimen en als het mogelijk is voor de kandidaat werken met machines.', '', 'Fysiek sterk, gemotiveerd, flexibel wat betreft werktijden, representatief.', 'SCHOONLOO', '8', '16', '', 'Normaal', 'Nee', 'Nee', 'Vakdeskundigheid toepassen', 'Materialen en middelen inzetten', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 596', '8440AN', 'HEERENVEEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Klusjesman (Wajong)', '377116', 'Agrarische Sector', 'Voor een camping in Ellertshaar zijn wij op zoek naar een klusjesman. U gaat de boer helpen met allerhande werkzaamheden zowel op de boerderij als op de camping. Werkzaamheden zijn o.a.: gras maaien, ', '', '', 'ELLERTSHAAR', '', '20', '', 'Normaal', 'Nee', 'Nee', 'Samenwerken en overleggen', 'Instructies en procedures opvolgen', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'De Vos van Steenwijklaan 75', '7902NP', 'HOOGEVEEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Schoonmaker (Wajong)', '377216', 'Interieurverzorging / industri‰le reiniging / schoonmaak', 'Voor een camping zijn wij op zoek naar een schoonmaker.', '', 'U kunt netjes werken.', 'ELLERTSHAAR', '20', '20', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'De Vos van Steenwijklaan 75', '7902NP', 'HOOGEVEEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Technisch medewerker (WAJONG)', '4955115', 'Industrie & Techniek', 'We zijn op zoek naar een handige kandidaat die affiniteit heeft met poolen, snookeren of biljarten. U gaat: ont-nieten en spijkers verwijderen van het biljart. Biljart tafel demonteren en opnieuw bekl', '', '', 'SCHOONOORD', '20', '20', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', 'Samenwerken en overleggen', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 786', '7550AT', 'HENGELO OV', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Schoonmaker (Wajong)', '512716', 'Industrie & Techniek', 'Voor een bedrijf in Hoogeveen zijn we op zoek naar een schoonmaker. U gaat de kantine, toiletten en de kantoren schoonmaken.', '', '', 'HOOGEVEEN', '16', '16', 'De werktijden zijn van 07.00 uur tot 16.00 uur.', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 7690', '8903JR', 'LEEUWARDEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker schoonmaak (Wajong)', '515616', 'Interieurverzorging / industri‰le reiniging / schoonmaak', 'Voor een fastfoodrestaurant in Stadskanaal zijn we op zoek naar een schoonmaakmedewerker. Uw werkzaamheden bestaan uit: het opruimen van het zwerfafval, schoonmaken van het magazijn, terras en speelto', '', 'Het aantal dagen is in overleg. De werktijden zijn van 07.15 uur tot ongeveer 12.30 uur.', 'STADSKANAAL', '20', '20', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Westerhaven 13', '9718AW', 'GRONINGEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Vakkenvuller (WAJONG)', '5656015', 'Detailhandel', 'Voor een bedrijf in Hoogeveen zijn we op zoek naar een vakkenvuller. Daarnaast staat u wanneer nodig klanten te woord.', '', 'U bent gemotiveerd en representatief.', 'HOOGEVEEN', '24', '28', '', 'Normaal', 'Nee', 'Nee', 'Vakdeskundigheid toepassen', 'Instructies en procedures opvolgen', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 990', '9400AZ', 'ASSEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Vrachtwagenpoetser (Wajong)', '5656215', 'Transport en logistiek', 'Voor een truckwash in Wijster/Staphorst/Assen en Hoogeveen zijn we op zoek naar een vrachtwagenpoetser. U maakt met behulp van een hoge druk reiniger vrachtwagens schoon.', '', '', 'HOOGEVEEN', '', '32', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 990', '9400AZ', 'ASSEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Lasser Klazienaveen *Wajong', '6101415', 'Industrie & Techniek', 'Wij zijn opzoek naar een lasser voor een bedrijf in Klazienaveen. Dit is een vacature voor mensen met een Wajong-uitkering.', 'Voorbereiden en lassen van stalen onderdelen volgens instructies. Uitvoeren visuele controles + maatvoeringen en het vastleggen van uitgevoerde handelingen en controles. Signaleren en communiceren van', '', 'KLAZIENAVEEN', '10', '20', '', 'Normaal', 'Nee', 'Nee', 'Materialen en middelen inzetten', 'Vakdeskundigheid toepassen', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Diamantlaan 1', '9743BA', 'GRONINGEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Subsidie-adviseur * Wajong', '6105615', 'Zakelijke dienstverlening', 'Voor ‚‚n van onze opdrachtgevers zijn wij op zoek naar subsidie-adviseur. Het betreft een aanstelling van 24-32 uur per week.', 'Als subsidie-adviseur werk je aan innovatieprojecten voor MKB-bedrijven in Noord-Nederland. Je begeleidt ondernemers bij het zoeken naar en aanvragen van subsidies. Dit loopt uiteen van het begeleiden', '', 'EMMEN', '24', '32', '', 'Normaal', 'Nee', 'Nee', 'Relaties bouwen en netwerken', 'Begeleiden', 'Analyseren', 'Presenteren', 'Overtuigen en be‹nvloeden', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Diamantlaan 1', '9743BA', 'GRONINGEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker onderhoud erf', '656116', 'Agrarische Sector', 'U houdt het erf constant schoon, u mest de stallen uit, u veegt aan, maait het gras, etc. Ervaring met paarden is niet noodzakelijk, maar wordt wel op prijs gesteld', '', 'U bent een aanpakker die vanwege het fysiek zware werk lichamelijk gezond is. U kunt, na instructie, zelfstandig werken. U wilt graag buiten werken en bent niet bang vieze handen te krijgen.', 'RUINERWOLD', '15', '15', 'De werkzaamheden zijn verdeeld over 5 dagen, 3 uur per dag. Het is ook mogelijk om in de weekenden te werken. De werkzaamheden starten met een proefplaatsing. Het opbouwen van uren is mogelijk. De int', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', 'Samenwerken en overleggen', '', '', '', 'E-mail met motivatie en CV', 'k.vanmeekeren@at-groep.nl', 'Marconistraat 15-a', '8013PK', 'ZWOLLE', 'Nederland', 'mevr. Meekeren,   van', 'coach''', '', 'k.vanmeekeren@at-groep.nl', 'mevr. Meekeren,   van', 'coach', '', 'k.vanmeekeren@at-groep.nl', '1'),
('Autopoetser (Wajong)', '884716', 'Transport en logistiek', 'Voor een tuningbedrijf in Hoogeveen zijn wij op zoek naar een autopoetser. Uw taken zijn zijn het schoonmaken en poetsen van auto''s.', '', 'Wij zijn op zoek naar een kandidaat uit Hoogeveen of directe omgeving. Dit betreft een parttime baan, uitbreiding van uren op termijn is bespreekbaar.', 'HOOGEVEEN', '20', '20', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 596', '8440AN', 'HEERENVEEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Productiemedewerker (Wajong)', '885116', 'Industrie & Techniek', 'Voor een bedrijf in de houtskeletbouw zijn wij op zoek naar een kandidaat die graag met hout werkt. De werkzaamheden zijn het bouwen van schuren, hokken e.d.', '', '', 'HOOGEVEEN', '40', '40', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 1172', '8900CD', 'LEEUWARDEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Klusjesman (Wajong)', '885416', 'Industrie & Techniek', 'Voor een organisatie in de chaletbouw zijn wij op zoek naar een klusjesman. U gaat schilderen, timmeren en andere voorkomende werkzaamheden.', '', '', 'DWINGELOO', '40', '40', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', 'Samenwerken en overleggen', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 1172', '8900CD', 'LEEUWARDEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker stortbordes (Wajong)', '887416', 'Industrie & Techniek', 'Voor een bedrijf in Coevorden zijn we op zoek naar een stortbordesmedewerker. U gaat klanten instructies geven voor het storten van afval/producten. U werkt samen met 1 andere collega. U werkt halve d', '', 'U bent woonachtig in omgeving: Coevorden.', 'COEVORDEN', '16', '16', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Jacob le Mairestraat 239', '7825XE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker wegenbouw (Wajong)', '890116', 'Industrie & Techniek', 'Wij zijn op zoek naar een gemotiveerde aanpakker met verantwoordelijkheidsgevoel. U ondersteunt de stratenmaker waar nodig. Mogelijkheden voor werkzaamheden op minikraan of shovel zijn aanwezig. Bij g', '', '', 'NIEUW-BUINEN', '40', '40', '', 'Normaal', 'Nee', 'Nee', 'Materialen en middelen inzetten', 'Vakdeskundigheid toepassen', 'Instructies en procedures opvolgen', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker schoonmaak (Wajong)', '890616', 'Interieurverzorging / industri‰le reiniging / schoonmaak', 'Wij zijn op zoek naar een schoonmaakmedewerker. U gaat machinaal de vloeren schrobben, oppoetsen van de vloer, dweilen, stofzuigen en het opblokken van de vloer, dit houdt het het insprayen van vloere', '', 'U heeft geen fysieke klachten.', 'EMMEN', '15', '20', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', '', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Blokhutbouwer (Wajong)', '890916', 'Industrie & Techniek', 'Uw werk bestaat uit de montage van blokhutten, aan aanbrengen van dakbedekking. u zorg voor de egalisatiebodem ter voorbereiding op plaatsing blokhutten. Daarnaast verricht u allround timmer- en schro', '', 'U werkt op verschillende locaties en maakt lange dagen.U komt uit de omgeving Coevorden.', 'EMMEN', '40', '40', '', 'Normaal', 'Nee', 'Nee', 'Instructies en procedures opvolgen', 'Vakdeskundigheid toepassen', 'Materialen en middelen inzetten', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Medewerker onderhoud (Wajong)', '900016', 'Industrie & Techniek', 'Voor een bedrijf in Dalen zijn wij op zoek naar een medewerker onderhoud. U gaat de stallen uitmesten en opstrooien. U brengt paarden van en naar de paddocks. U houdt het terrein schoon.', '', 'U heeft affiniteit met paarden.', 'DALEN', '20', '20', '', 'Normaal', 'Nee', 'Nee', 'Vakdeskundigheid toepassen', 'Materialen en middelen inzetten', 'Kwaliteit leveren', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Postbus 2235', '7801CE', 'EMMEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1'),
('Magazijnmedewerker (Wajong)', '901116', 'Industrie & Techniek', 'Uitvoeren van werkzaamheden ten aanzien van ontvangst, opslag en uitgifte van materialen en middelen in het centraal magazijn. Verrichten van allerlei klussen in en om het hoofdkantoor. Uitvoeren van ', '', '*Technisch inzicht*Fysiek in goede conditie*SVS opleiding glazenwasser, gevelreiniger dan wel vloerenonderhoud is een pre.*Basisveiligheidsopleiding is een pre.', 'COEVORDEN', '40', '40', '', 'Normaal', 'Nee', 'Nee', 'Vakdeskundigheid toepassen', 'Instructies en procedures opvolgen', '', '', '', 'E-mail met motivatie en CV', 'rianne.kasper@uwv.nl', 'Diamantlaan 1', '9743BA', 'GRONINGEN', 'Nederland', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', 'Kasper-Dubois, A.M.L.', 'Adviseur CWI', '591210214', 'rianne.kasper@uwv.nl', '1');

--
-- Indexen voor geëxporteerde tabellen
--

--
-- Indexen voor tabel `uwv_wajong`
--
ALTER TABLE `uwv_wajong`
 ADD PRIMARY KEY (`Vacaturenummer`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
